name: dev_studio_client

resolution: workspace

environment:
  sdk: '^3.5.0'

dependencies:
  built_collection:
  built_value:
  clock:
  collection:
  dev_studio_core:
    path: ../core
  device_frame:
  flutter:
    sdk: flutter
  flutter_markdown:
  flutter_svg:
  flutter_test:
    sdk: flutter
  http:
  image:
  logging:
  matcher:
  package_config:
  path:
  pool:
  process_runner:
  puppeteer:
  rxdart:
  stream_channel:
  test:
  test_api:
  web_socket_channel:
  yaml: