name: dev_studio

environment:
  sdk: '^3.5.0'

dependencies:
  built_collection:
  built_value:
  collection:
  dart_style:
  diacritic:
  device_frame:
  file_selector:
  flutter: { sdk: flutter }
  flutter_highlight:
  flutter_markdown:
  flutter_svg:
  flutter_web_plugins: { sdk: flutter }
  http:
  image:
  logging:
  os_detect:
  path:
  process_runner:
  puppeteer:
  quiver:
  rxdart:
  shelf:
  shelf_router:
  shelf_static:
  shelf_web_socket:
  stream_transform:
  test:
  url_launcher:
  vector_math:
  web_socket_channel:

dev_dependencies:
  build_runner:
  built_value_generator:
  flutter_test:
    sdk: flutter
  lints:
  project_tools:
    git:
      url: https://github.com/xvrh/project_tools.dart.git
      ref: '76d200c'

flutter:
  uses-material-design: true
  assets:
    - assets/
