name: Analyze pull requests
on:
  pull_request:

jobs:
  analyze_and_test:
    name: Flutter analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter doctor
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter test
        working-directory: client
      - run: flutter test
        working-directory: core
      - run: dart tool/format.dart
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: dart run build_runner build --delete-conflicting-outputs
        working-directory: client
      - run: dart run build_runner build --delete-conflicting-outputs
        working-directory: core
      - name: "check for uncommitted changes"
        run: |
          git diff --exit-code . \
          || (echo "##[error] found changed files after build. please run 'dart format .'" \
                   "and check in all changes" \
              && exit 1)
        shell: bash
